'use client'

import { useMemo, useState } from 'react'
import Image from 'next/image'
import { ArrowRight, Camera, ChevronDown, Truck } from 'lucide-react'
import { Header } from '@/components/Header'
import { ProductCard } from '@/components/ProductCard'
import { brands, categories, products } from '@/lib/products'

function Storefront() {
  const [query, setQuery] = useState('')
  const [brand, setBrand] = useState('Todas')
  const [category, setCategory] = useState('Todas')
  const filtered = useMemo(() => products.filter((product) => (brand === 'Todas' || product.brand === brand) && (category === 'Todas' || product.category === category) && `${product.name} ${product.notes}`.toLowerCase().includes(query.toLowerCase())), [brand, category, query])
  return <div className="min-h-screen bg-[#fbfaf7] text-[#2d211c]"><Header onSearch={setQuery} />
    <main>
      <section className="mx-auto grid max-w-7xl gap-0 px-5 pt-6 lg:grid-cols-[1.1fr_0.9fr] lg:px-8 lg:pt-8"><div className="relative flex min-h-[450px] flex-col justify-end overflow-hidden bg-[#2d211c] p-7 text-[#f9f3ea] sm:p-12 lg:min-h-[570px]"><Image src="/coffee-hero.png" alt="Café recién preparado junto a granos de café" fill priority className="object-cover opacity-80" sizes="(max-width: 1024px) 100vw, 55vw" /><div className="relative max-w-lg"><p className="mb-5 text-[11px] font-bold uppercase tracking-[0.24em] text-[#e8b49a]">Tostado con intención</p><h1 className="max-w-md font-serif text-5xl leading-[0.95] tracking-tight sm:text-7xl">El café que hace espacio para lo bueno.</h1><p className="mt-6 max-w-sm text-base leading-relaxed text-[#eaded4]">Orígenes honestos, tostados frescos y marcas que cuidan cada detalle de la taza.</p><a href="#catalogo" className="mt-8 inline-flex items-center gap-3 text-sm font-semibold text-white underline decoration-[#d98663] underline-offset-8">Descubre el catálogo <ArrowRight className="size-4" /></a></div></div><div className="flex flex-col justify-between bg-[#e9ddcf] p-7 sm:p-12 lg:min-h-[570px]"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-[#9b4b2d]">Selección de la semana</p><h2 className="mt-5 max-w-sm font-serif text-4xl leading-tight text-[#4b3025]">Pequeños rituales, grandes momentos.</h2></div><div className="mt-10"><div className="relative mx-auto aspect-square max-w-[310px] overflow-hidden rounded-full bg-[#c3a38a]"><Image src="/coffee-2.png" alt="Bolsa de café de especialidad" fill className="object-contain p-8" sizes="310px" /></div><div className="mt-7 flex items-end justify-between border-t border-[#c7b2a1] pt-5"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#9b7766]">Favorito de la casa</p><p className="mt-1 font-serif text-xl">Ethiopia Floral</p></div><span className="font-semibold">22,00 €</span></div></div></div></section>
      <section id="origenes" className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-16 sm:flex-row sm:items-end sm:justify-between lg:px-8"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-[#b65f3d]">Una buena selección</p><h2 className="mt-3 font-serif text-4xl tracking-tight sm:text-5xl">Encuentra tu próxima taza</h2></div><p className="max-w-sm text-sm leading-relaxed text-[#86756e]">Trabajamos con tostadores que comparten nuestra obsesión: que cada café llegue a ti en su mejor momento.</p></section>
      <section id="catalogo" className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="mb-8 flex flex-col gap-4 border-y border-[#e8ddd2] py-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2 overflow-x-auto pb-1">{brands.map((item) => <button key={item} onClick={() => setBrand(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold transition ${brand === item ? 'bg-[#2d211c] text-white' : 'text-[#806c62] hover:bg-[#f0e6db]'}`}>{item}</button>)}</div><label className="flex items-center gap-2 text-xs font-semibold text-[#806c62]">Tipo <select value={category} onChange={(event) => setCategory(event.target.value)} className="rounded-full border border-[#d9c9bd] bg-transparent px-3 py-2 outline-none">{categories.map((item) => <option key={item}>{item}</option>)}</select><ChevronDown className="-ml-7 mr-2 size-3 pointer-events-none" /></label></div><div className="grid grid-cols-2 gap-x-4 gap-y-12 sm:grid-cols-3 lg:grid-cols-4 lg:gap-x-6">{filtered.map((product) => <ProductCard key={product.id} product={product} />)}</div>{filtered.length === 0 && <p className="py-20 text-center text-[#86756e]">No encontramos ese café. Prueba con otra búsqueda.</p>}</section>
      <section id="historia" className="border-y border-[#e8ddd2] bg-[#f0e7dc]"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 py-14 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div className="flex items-center gap-5"><Truck className="size-8 text-[#b65f3d]" /><div><p className="font-serif text-xl">Envío gratis desde 45 €</p><p className="mt-1 text-sm text-[#806c62]">Recibe tu café fresco en 24–72 horas.</p></div></div><p className="max-w-md text-sm leading-relaxed text-[#806c62]">Una tienda independiente para descubrir cafés de todo el mundo, elegir sin prisa y volver a tus favoritos.</p><Camera className="hidden size-5 text-[#806c62] sm:block" /></div></section>
    </main><footer className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-8 text-xs text-[#806c62] sm:flex-row sm:items-center sm:justify-between lg:px-8"><p>© 2026 El Buen Grano</p><p>Hecho para quienes disfrutan el ritual.</p></footer>
  </div>
}

export default function Page() { return <Storefront /> }
